
package igu;


public class panel2 extends javax.swing.JPanel {

    //public static char selec2;
    
    public panel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_panel2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rb_tramo = new javax.swing.JRadioButton();
        rb_paralelo = new javax.swing.JRadioButton();
        rb_serie = new javax.swing.JRadioButton();
        rb_caudal = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(251, 253, 253));
        setMinimumSize(new java.awt.Dimension(800, 320));
        setPreferredSize(new java.awt.Dimension(800, 320));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setText("¿Que desea hacer?");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        rb_tramo.setBackground(new java.awt.Color(251, 253, 253));
        grp_panel2.add(rb_tramo);
        rb_tramo.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        rb_tramo.setSelected(true);
        rb_tramo.setText("Cálculo de un tramo de tubería");
        rb_tramo.setToolTipText("");

        rb_paralelo.setBackground(new java.awt.Color(251, 253, 253));
        grp_panel2.add(rb_paralelo);
        rb_paralelo.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        rb_paralelo.setText("Crear arreglo de tuberías en PARALELO");
        rb_paralelo.setToolTipText("");

        rb_serie.setBackground(new java.awt.Color(251, 253, 253));
        grp_panel2.add(rb_serie);
        rb_serie.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        rb_serie.setText("Crear arreglo de tubería en SERIE");
        rb_serie.setToolTipText("");

        rb_caudal.setBackground(new java.awt.Color(251, 253, 253));
        grp_panel2.add(rb_caudal);
        rb_caudal.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        rb_caudal.setText("Aumentar caudal de una tubería existente, sin afectar caída de presión");
        rb_caudal.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_paralelo)
                            .addComponent(rb_tramo)
                            .addComponent(rb_serie)
                            .addComponent(rb_caudal)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel1)))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_tramo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_paralelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_serie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_caudal)
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grp_panel2;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JRadioButton rb_caudal;
    public javax.swing.JRadioButton rb_paralelo;
    public javax.swing.JRadioButton rb_serie;
    public javax.swing.JRadioButton rb_tramo;
    // End of variables declaration//GEN-END:variables
}
